version: "3.8"
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bug_tracker
      SPRING_DATASOURCE_USERNAME: dimitris
      SPRING_DATASOURCE_PASSWORD: 1234

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: bug_tracker
      POSTGRES_USER: dimitris
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
